const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"维修员管理",
			            "menuJump":"列表",
			            "tableName":"weixiuyuan"
			        }
			    ],
			    "menu":"维修员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"员工管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"员工管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"材料信息管理",
                        "menuJump":"列表",
                        "tableName":"cailiao"
                    }
                ],
                "menu":"材料信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出入库管理",
                        "menuJump":"列表",
                        "tableName":"cailiaoChuruInout"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出入库列表管理",
                        "menuJump":"列表",
                        "tableName":"cailiaoChuruInoutList"
                    }
                ],
                "menu":"出入库管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"产品信息管理",
                        "menuJump":"列表",
                        "tableName":"chanpin"
                    }
                ],
                "menu":"产品信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
							"新增",
							"修改",
                            "删除"
                        ],
                        "menu":"顾客订单管理",
                        "menuJump":"列表",
                        "tableName":"gukedingdan"
                    }
                ],
                "menu":"顾客订单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"生产计划管理",
                        "menuJump":"列表",
                        "tableName":"shengcanjihua"
                    }
                ],
                "menu":"生产计划管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"设备信息管理",
			            "menuJump":"列表",
			            "tableName":"shebei"
			        }
			    ],
			    "menu":"设备信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"设备检修管理",
			            "menuJump":"列表",
			            "tableName":"shebeijianxiu"
			        }
			    ],
			    "menu":"设备检修管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"质量监控管理",
                        "menuJump":"列表",
                        "tableName":"zhiljiankong"
                    }
                ],
                "menu":"质量监控管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"部门管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryBumen"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"材料类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryCailiao"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"产品类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryChanpin"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"设备类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryShebei"
			        }
			    ],
			    "menu":"基础数据管理"
			}
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"材料信息管理",
	                    "menuJump":"列表",
	                    "tableName":"cailiao"
	                }
	            ],
	            "menu":"材料信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"出入库管理",
	                    "menuJump":"列表",
	                    "tableName":"cailiaoChuruInout"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"出入库列表管理",
	                    "menuJump":"列表",
	                    "tableName":"cailiaoChuruInoutList"
	                }
	            ],
	            "menu":"出入库管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"产品信息管理",
	                    "menuJump":"列表",
	                    "tableName":"chanpin"
	                }
	            ],
	            "menu":"产品信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"新增",
							"修改"
	                    ],
	                    "menu":"顾客订单管理",
	                    "menuJump":"列表",
	                    "tableName":"gukedingdan"
	                }
	            ],
	            "menu":"顾客订单管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"生产计划管理",
	                    "menuJump":"列表",
	                    "tableName":"shengcanjihua"
	                }
	            ],
	            "menu":"生产计划管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
	                        "新增",
	                        "修改"
			            ],
			            "menu":"设备信息管理",
			            "menuJump":"列表",
			            "tableName":"shebei"
			        }
			    ],
			    "menu":"设备信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"设备检修管理",
			            "menuJump":"列表",
			            "tableName":"shebeijianxiu"
			        }
			    ],
			    "menu":"设备检修管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"质量监控管理",
	                    "menuJump":"列表",
	                    "tableName":"zhiljiankong"
	                }
	            ],
	            "menu":"质量监控管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"员工",
	    "tableName":"yonghu"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"设备信息管理",
			            "menuJump":"列表",
			            "tableName":"shebei"
			        }
			    ],
			    "menu":"设备信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增"
			            ],
			            "menu":"设备检修管理",
			            "menuJump":"列表",
			            "tableName":"shebeijianxiu"
			        }
			    ],
			    "menu":"设备检修管理"
			}
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"维修员",
	    "tableName":"weixiuyuan"
	}
]
    }
}
export default menu;
